name: GitHub Stats

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  stats:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: Generate GitHub Stats
        uses: cicirello/user-statistician@v1
        with:
          image-file: userstats.svg
          custom-title: "Atividade no GitHub"
          colors: dark-dimmed
          max-languages: 6
          locale: pt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}