name: GitHub Stats

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: main

      - name: Sync with main
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git pull --rebase origin main

      - name: Generate GitHub Stats
        uses: cicirello/user-statistician@v1
        with:
          image-file: userstats.svg
          custom-title: "Atividade no GitHub"
          colors: dark-dimmed
          max-languages: 6
          locale: pt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}